# Generated by Django 5.1.3 on 2026-03-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_category_id_alter_item_id_client_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="barcode",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="item",
            name="stock_quantity",
            field=models.IntegerField(default=0),
        ),
    ]
