# Generated by Django 5.1.3 on 2026-07-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_item_barcode_item_stock_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
